-------Ratesheet tables:

USE [NewColumbus]
GO

/****** Object:  Table [dbo].[RATESHEET_APPLICATION_PARAM]    Script Date: 1/21/2020 8:40:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RATESHEET_APPLICATION_PARAM](
	[AUTOGEN_RS_PARAM_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PARAM_KEY] [varchar](100) NULL,
	[PARAM_VALUE] [varchar](max) NULL,
	[STATUS] [varchar](20) NULL,
	[CREATED_BY] [varchar](50) NULL,
	[UPDATED_BY] [varchar](50) NULL,
	[REC_ADD_DT] [datetime] NULL,
	[REC_UPDATE_DT] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[RATESHEET_APPLICATION_PARAM] ADD  CONSTRAINT [DF_RATESHEET_APPLICATION_PARAM_REC_ADD_DT]  DEFAULT (getdate()) FOR [REC_ADD_DT]
GO


USE [NewColumbus]
GO

/****** Object:  Table [dbo].[RATESHEET_ERROR_LOG]    Script Date: 1/21/2020 8:42:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RATESHEET_ERROR_LOG](
	[AUTOGEN_RS_ERROR_LOG_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[AUTOGEN_RS_ID] [bigint] NULL,
	[RS_NAME] [varchar](100) NULL,
	[FILE_NAME] [varchar](200) NULL,
	[FILE_CONTENT] [varbinary](max) NULL,
	[ERROR_MSG] [varchar](max) NULL,
	[STATUS] [varchar](20) NULL,
	[CREATED_BY] [varchar](50) NULL,
	[UPDATED_BY] [varchar](50) NULL,
	[REC_ADD_DT] [datetime] NULL,
	[REC_UPDATE_DT] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[RATESHEET_ERROR_LOG] ADD  CONSTRAINT [DF_RATESHEET_ERROR_LOG_REC_ADD_DT]  DEFAULT (getdate()) FOR [REC_ADD_DT]
GO


USE [NewColumbus]
GO

/****** Object:  Table [dbo].[RATESHEET_MAPPING]    Script Date: 1/21/2020 8:43:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RATESHEET_MAPPING](
	[AUTOGEN_RS_MAP_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SECTOR_CODE] [varchar](20) NULL,
	[SECTOR_NAME] [varchar](max) NULL,
	[CATEGORY_CODE] [varchar](20) NULL,
	[CATEGORY_NAME] [varchar](max) NULL,
	[CITY_CODE] [varchar](20) NULL,
	[CITY_NAME] [varchar](max) NULL,
	[COUNTRY_CODE] [varchar](20) NULL,
	[COUNTRY_NAME] [varchar](max) NULL,
	[FROM_DATE] [date] NULL,
	[TO_DATE] [date] NULL,
	[AUTOGEN_RS_ID] [bigint] NOT NULL,
	[RS_NAME] [varchar](max) NULL,
	[PARTY_CODE] [varchar](20) NULL,
	[PARTY_NAME] [varchar](max) NULL,
	[STATUS] [varchar](20) NULL,
	[REC_ADD_DT] [datetime] NULL,
	[REC_UPDATE_DT] [datetime] NULL,
	[CREATED_BY] [varchar](50) NULL,
	[UPDATED_BY] [varchar](50) NULL,
	[DISPLAY_NAME] [varchar](max) NULL,
 CONSTRAINT [UC_RATESHEET_MAPPING1] UNIQUE NONCLUSTERED 
(
	[AUTOGEN_RS_ID] ASC,
	[PARTY_CODE] ASC,
	[SECTOR_CODE] ASC,
	[CATEGORY_CODE] ASC,
	[CITY_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



USE [NewColumbus]
GO

/****** Object:  Table [dbo].[RATESHEET_MGT]    Script Date: 1/21/2020 8:43:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RATESHEET_MGT](
	[AUTOGEN_RS_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[RS_NAME] [varchar](100) NOT NULL,
	[RS_DESC] [varchar](max) NULL,
	[EMAIL_IDS] [varchar](max) NULL,
	[AGENT_CODE] [varchar](50) NULL,
	[AGENT_NAME] [varchar](50) NULL,
	[DIVISION_ID] [varchar](50) NULL,
	[DIVISION_NAME] [varchar](50) NULL,
	[SEND_RATESHEET] [varchar](20) NULL,
	[SEND_UPDATES] [varchar](20) NULL,
	[SHEET_PASSWORD] [varchar](100) NULL,
	[STATUS] [varchar](20) NULL,
	[CREATED_BY] [varchar](50) NULL,
	[UPDATED_BY] [varchar](50) NULL,
	[REC_ADD_DT] [datetime] NULL,
	[REC_UPDATE_DT] [datetime] NULL,
 CONSTRAINT [UC_RATESHEET_MGT1] UNIQUE NONCLUSTERED 
(
	[DIVISION_ID] ASC,
	[RS_NAME] ASC,
	[AGENT_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[RATESHEET_MGT] ADD  CONSTRAINT [DF_RATESHEET_MGT_REC_ADD_DT]  DEFAULT (getdate()) FOR [REC_ADD_DT]
GO


USE [NewColumbus]
GO

/****** Object:  Table [dbo].[RATESHEET_TIME_LOG]    Script Date: 1/21/2020 8:43:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RATESHEET_TIME_LOG](
	[AUTOGEN_RS_TIME_LOG_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[AUTOGEN_RS_ID] [bigint] NULL,
	[RS_NAME] [varchar](100) NULL,
	[PARTY_CODE] [varchar](20) NULL,
	[PARTY_NAME] [varchar](max) NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[TOTAL_TIME] [int] NULL,
	[CREATED_BY] [varchar](50) NULL,
	[REC_ADD_DT] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[RATESHEET_TIME_LOG] ADD  CONSTRAINT [DF_RATESHEET_TIME_LOG_REC_ADD_DT]  DEFAULT (getdate()) FOR [REC_ADD_DT]
GO


USE [NewColumbus]
GO

/****** Object:  Table [dbo].[RATESHEET_UPDATES]    Script Date: 2/10/2020 1:20:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RATESHEET_UPDATES](
	[AUTOGEN_RS_UPDATES_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[UPDATE_NAME] [varchar](50) NULL,
	[PARTY_CODE] [varchar](50) NULL,
	[PARTY_NAME] [varchar](max) NULL,
	[UPDATE_DETAILS] [varchar](500) NULL,
	[VALID_FROM] [datetime] NULL,
	[VALID_TILL] [datetime] NULL,
	[INTERNAL_NOTE] [varchar](max) NULL,
	[AUTOGEN_RS_ID] [bigint] NULL,
	[RS_NAME] [varchar](100) NULL,
	[STATUS] [varchar](20) NULL,
	[CREATED_BY] [varchar](50) NULL,
	[UPDATED_BY] [varchar](50) NULL,
	[REC_ADD_DT] [datetime] NULL,
	[REC_UPDATE_DT] [datetime] NULL,
 CONSTRAINT [UC_RATESHEET_UPDATES1] UNIQUE NONCLUSTERED 
(
	[AUTOGEN_RS_ID] ASC,
	[UPDATE_NAME] ASC,
	[PARTY_CODE] ASC,
	[VALID_FROM] ASC,
	[VALID_TILL] ASC,
	[UPDATE_DETAILS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[RATESHEET_UPDATES] ADD  CONSTRAINT [DF_RATESHEET_UPDATES_REC_ADD_DT]  DEFAULT (getdate()) FOR [REC_ADD_DT]
GO


USE [NewColumbus]
GO

/****** Object:  Table [dbo].[RATESHEET_USERS]    Script Date: 2/10/2020 1:21:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RATESHEET_USERS](
	[AUTOGEN_USERS_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_ID] [varchar](100) NOT NULL,
	[PASSWORD] [varchar](500) NULL,
	[FIRST_NAME] [varchar](50) NULL,
	[LAST_NAME] [varchar](50) NULL,
	[EMAIL] [varchar](50) NULL,
	[MOBILE_NUMBER] [varchar](50) NULL,
	[STATUS] [varchar](20) NULL,
	[CREATED_BY] [varchar](50) NULL,
	[UPDATED_BY] [varchar](50) NULL,
	[REC_ADD_DT] [datetime] NULL,
	[REC_UPDATE_DT] [datetime] NULL,
 CONSTRAINT [UC_RATESHEET_USERS1] UNIQUE NONCLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RATESHEET_USERS] ADD  CONSTRAINT [DF_RATESHEET_USERS_REC_ADD_DT]  DEFAULT (getdate()) FOR [REC_ADD_DT]
GO


USE [NewColumbus]
GO

/****** Object:  Table [dbo].[RATESHEET_TOKEN_DETAILS]    Script Date: 2/10/2020 1:21:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RATESHEET_TOKEN_DETAILS](
	[AUTOGEN_TOKEN_DETAILS_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_ID] [varchar](100) NOT NULL,
	[TOKEN] [varchar](1000) NULL,
	[REFRESH_TOKEN] [varchar](1000) NULL,
	[expiry_seconds] [varchar](11) NULL,
	[expiry_Date] [datetime] NULL,
	[STATUS] [varchar](20) NULL,
	[CREATED_BY] [varchar](50) NULL,
	[UPDATED_BY] [varchar](50) NULL,
	[REC_ADD_DT] [datetime] NULL,
	[REC_UPDATE_DT] [datetime] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RATESHEET_TOKEN_DETAILS] ADD  CONSTRAINT [DF_rs_token_details_REC_ADD_DT]  DEFAULT (getdate()) FOR [REC_ADD_DT]
GO


USE [NewColumbus]
GO

/****** Object:  Table [dbo].[RATESHEET_LOGIN_DETAILS]    Script Date: 2/10/2020 1:21:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RATESHEET_LOGIN_DETAILS](
	[AUTOGEN_LOGIN_DETAILS_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_ID] [varchar](20) NULL,
	[LOGIN_TIME] [datetime] NOT NULL,
	[LOGOUT_TIME] [datetime] NULL,
	[NO_OF_ATTEMPT] [bigint] NULL,
	[REMARKS] [varchar](100) NULL,
	[CREATED_BY] [varchar](30) NULL,
	[UPDATED_BY] [varchar](30) NULL,
	[REC_ADD_DT] [datetime] NULL,
	[REC_UPDATE_DT] [datetime] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RATESHEET_LOGIN_DETAILS] ADD  DEFAULT (NULL) FOR [EMPLOYEE_ID]
GO

ALTER TABLE [dbo].[RATESHEET_LOGIN_DETAILS] ADD  DEFAULT (getdate()) FOR [LOGIN_TIME]
GO

ALTER TABLE [dbo].[RATESHEET_LOGIN_DETAILS] ADD  DEFAULT (NULL) FOR [LOGOUT_TIME]
GO

ALTER TABLE [dbo].[RATESHEET_LOGIN_DETAILS] ADD  DEFAULT (NULL) FOR [NO_OF_ATTEMPT]
GO

ALTER TABLE [dbo].[RATESHEET_LOGIN_DETAILS] ADD  DEFAULT (NULL) FOR [REMARKS]
GO

ALTER TABLE [dbo].[RATESHEET_LOGIN_DETAILS] ADD  DEFAULT (NULL) FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[RATESHEET_LOGIN_DETAILS] ADD  DEFAULT (NULL) FOR [UPDATED_BY]
GO

ALTER TABLE [dbo].[RATESHEET_LOGIN_DETAILS] ADD  DEFAULT (getdate()) FOR [REC_ADD_DT]
GO

ALTER TABLE [dbo].[RATESHEET_LOGIN_DETAILS] ADD  DEFAULT (NULL) FOR [REC_UPDATE_DT]
GO



