
--##### UPDATE_TYPES #####--
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','CONTRACT','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','REVISED CONTRACT','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','NEW OFFER','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','REVISED OFFER','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','ADDENDUM','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','UPDATES','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','WITHDRAWAL','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','CORRECTION','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','ADDITIONAL INFO','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','ROOM NAME CHANGE','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','HOTEL NAME CHANGE','ACTIVE','SYSTEM');
INSERT INTO RATESHEET_APPLICATION_PARAM (PARAM_KEY, PARAM_VALUE,STATUS,CREATED_BY) VALUES ('UPDATE_TYPE','INTERNAL UPDATE','ACTIVE','SYSTEM');

